require "user.conf.notify"
require "user.conf.nvim-tree"
require "user.conf.cmp"
require "user.conf.telescope"
require "user.conf.autopairs"
require "user.conf.comment"
require "user.conf.gitsigns"
require "user.conf.vgit"
require "user.conf.bufferline"
require "user.conf.lualine"
require "user.conf.toggleterm"
require "user.conf.project"
require "user.conf.impatient"
require "user.conf.alpha"
require "user.conf.whichkey"
require "user.conf.autocommands"
require "user.conf.hop"
require "user.conf.todo-comments"
require "user.conf.trouble"
require "user.conf.filetype"
require "user.conf.vim-cmake"
require "user.conf.indentline"
require "user.conf.preview-markdown"
require "user.conf.treesitter"
require "user.conf.treesitter-context"
-- require "user.conf.nvim_context_vt"
require "user.conf.aerial"
require "user.conf.vim-ultest"
require "user.conf.sniprun"
require "user.conf.nvim-neoclip"
require "user.conf.winshift"
require "user.conf.high-str"
require "user.conf.vim-translator"
-- require "user.conf.symbols-outline"
-- require "user.conf.vista"
